version: '3'
services:
  minio:
    image: minio/minio:RELEASE.2021-04-06T23-11-00Z
    container_name: minio
    ports:
      - "9000:9000"
    volumes:
      - "./minio/data:/data"
      - "./minio/config:/root/.minio/"
    environment:
      MINIO_ACCESS_KEY: "minio"
      MINIO_SECRET_KEY: "minio123"
    command: server /data
    restart: always