# rabbitmq快速安装版（延迟插件需要手动配置）
version: '3'
services:
  rabbitmq:
    image: rabbitmq:3.8-management      # 镜像
    container_name: rabbitmq            # 容器名为'rabbitmq'
    hostname: my-rabbit                # 主机名(集群的时候需要这个)
    restart: always                     # 设置docker重启时容器也重启 
    environment:                        # 设置环境变量,相当于docker run命令中的-e
      TZ: Asia/Shanghai                 
      LANG: en_US.UTF-8                 
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: 123456     
    volumes:                            # 数据卷挂载路径设置,将本机目录映射到容器目录
      - "./rabbitmq/data:/var/lib/rabbitmq"
      - "./rabbitmq/log:/var/log/rabbitmq"   # 防止log日志报failed to open log file
    ports:                              # 配置端口映射
      - "5672:5672"                     # 生产者、消费者通信的端口
      - "15672:15672"                   # 管理面板的端口